version: '3.8'

services:
  db:
    container_name: dockerMySQL
    build: 
      context: ./docker
      dockerfile: Dockerfile.db
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: test
      MYSQL_PASSWORD: password


volumes:
  db-data:
