// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	CategoryID   string         `gorm:"column:category_id;type:varchar(36);primaryKey" json:"category_id"`
	CategoryName string         `gorm:"column:category_name;type:varchar(512);not null" json:"category_name"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
