// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProduct = "product"

// Product mapped from table <product>
type Product struct {
	ProductID     string       `gorm:"column:product_id;type:varchar(36);primaryKey;index:idx_product_cover,priority:1" json:"product_id"`
	SubCategoryID *string      `gorm:"column:sub_category_id;type:varchar(36);index:idx_product_cover,priority:3" json:"sub_category_id"`
	ProductName   string       `gorm:"column:product_name;type:varchar(1024);not null" json:"product_name"`
	Price         *int32       `gorm:"column:price;type:int unsigned;index:idx_product_cover,priority:2" json:"price"`
	TaxStatus     int32        `gorm:"column:tax_status;type:int unsigned;not null;index:idx_product_cover,priority:4" json:"tax_status"`
	SubCategory   *SubCategory `gorm:"foreignKey:SubCategoryID;references:SubCategoryID" json:"sub_category"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
