// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSalesProduct = "sales_product"

// SalesProduct mapped from table <sales_product>
type SalesProduct struct {
	SalesID     string    `gorm:"column:sales_id;type:varchar(36);primaryKey" json:"sales_id"`
	ProductID   string    `gorm:"column:product_id;type:varchar(36);primaryKey;index:idx_sales_product_cover,priority:2" json:"product_id"`
	ProductName string    `gorm:"column:product_name;type:varchar(1024);not null" json:"product_name"`
	Count_      int32     `gorm:"column:count;type:int unsigned;not null;index:idx_sales_product_cover,priority:4" json:"count"`
	SalesPrice  int64     `gorm:"column:sales_price;type:bigint unsigned;not null" json:"sales_price"`
	SalesDate   time.Time `gorm:"column:sales_date;type:datetime;primaryKey;index:idx_sales_product_cover,priority:1" json:"sales_date"`
	TaxStatus   int32     `gorm:"column:tax_status;type:int unsigned;not null" json:"tax_status"`
	IsReturned  *int32    `gorm:"column:is_returned;type:int unsigned;index:idx_sales_product_cover,priority:3" json:"is_returned"`
	Product     *Product  `gorm:"foreignKey:ProductID;references:ProductID" json:"product"`
}

// TableName SalesProduct's table name
func (*SalesProduct) TableName() string {
	return TableNameSalesProduct
}
