// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSale = "sales"

// Sale mapped from table <sales>
type Sale struct {
	SalesID         string          `gorm:"column:sales_id;type:varchar(36);primaryKey" json:"sales_id"`
	SalesDate       time.Time       `gorm:"column:sales_date;type:datetime;primaryKey" json:"sales_date"`
	TotalSales      int64           `gorm:"column:total_sales;type:bigint unsigned;not null" json:"total_sales"`
	TotalPrice      int64           `gorm:"column:total_price;type:bigint unsigned;not null" json:"total_price"`
	TotalTax        int64           `gorm:"column:total_tax;type:bigint unsigned;not null" json:"total_tax"`
	TotalReducedTax *int64          `gorm:"column:total_reduced_tax;type:bigint unsigned" json:"total_reduced_tax"`
	IsReturned      *int32          `gorm:"column:is_returned;type:int unsigned" json:"is_returned"`
	ReturnedAt      *time.Time      `gorm:"column:returned_at;type:datetime" json:"returned_at"`
	SalesProduct    []*SalesProduct `gorm:"foreignKey:SalesID;references:SalesID" json:"sales_product"`
}

// TableName Sale's table name
func (*Sale) TableName() string {
	return TableNameSale
}
