// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSubCategory = "sub_category"

// SubCategory mapped from table <sub_category>
type SubCategory struct {
	SubCategoryID   string    `gorm:"column:sub_category_id;type:varchar(36);primaryKey;index:idx_sub_category_cover,priority:1" json:"sub_category_id"`
	CategoryID      *string   `gorm:"column:category_id;type:varchar(36);index:category_id,priority:1;index:idx_sub_category_cover,priority:2" json:"category_id"`
	SubCategoryName string    `gorm:"column:sub_category_name;type:varchar(1024);not null" json:"sub_category_name"`
	Category        *Category `json:"category"`
}

// TableName SubCategory's table name
func (*SubCategory) TableName() string {
	return TableNameSubCategory
}
